web:
  build: .
  volumes:
   - .:/code
  links:
   - redis
  expose:
   - "5000"
redis:
  image: redis
lb:
  image: tutum/haproxy
  links:
   - web
  ports:
   - "80:80"
   - "1936:1936"
  environment:
   - STATS_PORT=1936
   - BACKEND_PORT=5000
   - BALANCE=roundrobin
